// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TweetsService.proto

package com.talentica.tweetsservicegrpc;

public interface SaveResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isSaved = 1;</code>
   */
  boolean getIsSaved();
}
