// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TweetsService.proto

package com.talentica.tweetsservicegrpc;

/**
 * Protobuf type {@code TweetData}
 */
public  final class TweetData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TweetData)
    TweetDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TweetData.newBuilder() to construct.
  private TweetData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TweetData() {
    id_ = "";
    text_ = "";
    authorId_ = "";
    createdAt_ = "";
    negativeScore_ = 0D;
    neutralScore_ = 0D;
    positiveScore_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TweetData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            text_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            authorId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            createdAt_ = s;
            break;
          }
          case 41: {

            negativeScore_ = input.readDouble();
            break;
          }
          case 49: {

            neutralScore_ = input.readDouble();
            break;
          }
          case 57: {

            positiveScore_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.talentica.tweetsservicegrpc.TweetsServiceOuterClass.internal_static_TweetData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.talentica.tweetsservicegrpc.TweetsServiceOuterClass.internal_static_TweetData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.talentica.tweetsservicegrpc.TweetData.class, com.talentica.tweetsservicegrpc.TweetData.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEXT_FIELD_NUMBER = 2;
  private volatile java.lang.Object text_;
  /**
   * <code>string text = 2;</code>
   */
  public java.lang.String getText() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      text_ = s;
      return s;
    }
  }
  /**
   * <code>string text = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTextBytes() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      text_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTHORID_FIELD_NUMBER = 3;
  private volatile java.lang.Object authorId_;
  /**
   * <code>string authorId = 3;</code>
   */
  public java.lang.String getAuthorId() {
    java.lang.Object ref = authorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      authorId_ = s;
      return s;
    }
  }
  /**
   * <code>string authorId = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAuthorIdBytes() {
    java.lang.Object ref = authorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      authorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATEDAT_FIELD_NUMBER = 4;
  private volatile java.lang.Object createdAt_;
  /**
   * <code>string createdAt = 4;</code>
   */
  public java.lang.String getCreatedAt() {
    java.lang.Object ref = createdAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdAt_ = s;
      return s;
    }
  }
  /**
   * <code>string createdAt = 4;</code>
   */
  public com.google.protobuf.ByteString
      getCreatedAtBytes() {
    java.lang.Object ref = createdAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createdAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEGATIVESCORE_FIELD_NUMBER = 5;
  private double negativeScore_;
  /**
   * <code>double negativeScore = 5;</code>
   */
  public double getNegativeScore() {
    return negativeScore_;
  }

  public static final int NEUTRALSCORE_FIELD_NUMBER = 6;
  private double neutralScore_;
  /**
   * <code>double neutralScore = 6;</code>
   */
  public double getNeutralScore() {
    return neutralScore_;
  }

  public static final int POSITIVESCORE_FIELD_NUMBER = 7;
  private double positiveScore_;
  /**
   * <code>double positiveScore = 7;</code>
   */
  public double getPositiveScore() {
    return positiveScore_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getTextBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, text_);
    }
    if (!getAuthorIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, authorId_);
    }
    if (!getCreatedAtBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, createdAt_);
    }
    if (negativeScore_ != 0D) {
      output.writeDouble(5, negativeScore_);
    }
    if (neutralScore_ != 0D) {
      output.writeDouble(6, neutralScore_);
    }
    if (positiveScore_ != 0D) {
      output.writeDouble(7, positiveScore_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getTextBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, text_);
    }
    if (!getAuthorIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, authorId_);
    }
    if (!getCreatedAtBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, createdAt_);
    }
    if (negativeScore_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, negativeScore_);
    }
    if (neutralScore_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, neutralScore_);
    }
    if (positiveScore_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, positiveScore_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.talentica.tweetsservicegrpc.TweetData)) {
      return super.equals(obj);
    }
    com.talentica.tweetsservicegrpc.TweetData other = (com.talentica.tweetsservicegrpc.TweetData) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && getText()
        .equals(other.getText());
    result = result && getAuthorId()
        .equals(other.getAuthorId());
    result = result && getCreatedAt()
        .equals(other.getCreatedAt());
    result = result && (
        java.lang.Double.doubleToLongBits(getNegativeScore())
        == java.lang.Double.doubleToLongBits(
            other.getNegativeScore()));
    result = result && (
        java.lang.Double.doubleToLongBits(getNeutralScore())
        == java.lang.Double.doubleToLongBits(
            other.getNeutralScore()));
    result = result && (
        java.lang.Double.doubleToLongBits(getPositiveScore())
        == java.lang.Double.doubleToLongBits(
            other.getPositiveScore()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getText().hashCode();
    hash = (37 * hash) + AUTHORID_FIELD_NUMBER;
    hash = (53 * hash) + getAuthorId().hashCode();
    hash = (37 * hash) + CREATEDAT_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedAt().hashCode();
    hash = (37 * hash) + NEGATIVESCORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getNegativeScore()));
    hash = (37 * hash) + NEUTRALSCORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getNeutralScore()));
    hash = (37 * hash) + POSITIVESCORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPositiveScore()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.talentica.tweetsservicegrpc.TweetData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talentica.tweetsservicegrpc.TweetData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talentica.tweetsservicegrpc.TweetData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talentica.tweetsservicegrpc.TweetData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talentica.tweetsservicegrpc.TweetData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.talentica.tweetsservicegrpc.TweetData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.talentica.tweetsservicegrpc.TweetData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.talentica.tweetsservicegrpc.TweetData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.talentica.tweetsservicegrpc.TweetData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.talentica.tweetsservicegrpc.TweetData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.talentica.tweetsservicegrpc.TweetData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.talentica.tweetsservicegrpc.TweetData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.talentica.tweetsservicegrpc.TweetData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TweetData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TweetData)
      com.talentica.tweetsservicegrpc.TweetDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.talentica.tweetsservicegrpc.TweetsServiceOuterClass.internal_static_TweetData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.talentica.tweetsservicegrpc.TweetsServiceOuterClass.internal_static_TweetData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.talentica.tweetsservicegrpc.TweetData.class, com.talentica.tweetsservicegrpc.TweetData.Builder.class);
    }

    // Construct using com.talentica.tweetsservicegrpc.TweetData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      text_ = "";

      authorId_ = "";

      createdAt_ = "";

      negativeScore_ = 0D;

      neutralScore_ = 0D;

      positiveScore_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.talentica.tweetsservicegrpc.TweetsServiceOuterClass.internal_static_TweetData_descriptor;
    }

    @java.lang.Override
    public com.talentica.tweetsservicegrpc.TweetData getDefaultInstanceForType() {
      return com.talentica.tweetsservicegrpc.TweetData.getDefaultInstance();
    }

    @java.lang.Override
    public com.talentica.tweetsservicegrpc.TweetData build() {
      com.talentica.tweetsservicegrpc.TweetData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.talentica.tweetsservicegrpc.TweetData buildPartial() {
      com.talentica.tweetsservicegrpc.TweetData result = new com.talentica.tweetsservicegrpc.TweetData(this);
      result.id_ = id_;
      result.text_ = text_;
      result.authorId_ = authorId_;
      result.createdAt_ = createdAt_;
      result.negativeScore_ = negativeScore_;
      result.neutralScore_ = neutralScore_;
      result.positiveScore_ = positiveScore_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.talentica.tweetsservicegrpc.TweetData) {
        return mergeFrom((com.talentica.tweetsservicegrpc.TweetData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.talentica.tweetsservicegrpc.TweetData other) {
      if (other == com.talentica.tweetsservicegrpc.TweetData.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getText().isEmpty()) {
        text_ = other.text_;
        onChanged();
      }
      if (!other.getAuthorId().isEmpty()) {
        authorId_ = other.authorId_;
        onChanged();
      }
      if (!other.getCreatedAt().isEmpty()) {
        createdAt_ = other.createdAt_;
        onChanged();
      }
      if (other.getNegativeScore() != 0D) {
        setNegativeScore(other.getNegativeScore());
      }
      if (other.getNeutralScore() != 0D) {
        setNeutralScore(other.getNeutralScore());
      }
      if (other.getPositiveScore() != 0D) {
        setPositiveScore(other.getPositiveScore());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.talentica.tweetsservicegrpc.TweetData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.talentica.tweetsservicegrpc.TweetData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object text_ = "";
    /**
     * <code>string text = 2;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string text = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string text = 2;</code>
     */
    public Builder setText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      text_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string text = 2;</code>
     */
    public Builder clearText() {
      
      text_ = getDefaultInstance().getText();
      onChanged();
      return this;
    }
    /**
     * <code>string text = 2;</code>
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      text_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object authorId_ = "";
    /**
     * <code>string authorId = 3;</code>
     */
    public java.lang.String getAuthorId() {
      java.lang.Object ref = authorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string authorId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAuthorIdBytes() {
      java.lang.Object ref = authorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string authorId = 3;</code>
     */
    public Builder setAuthorId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      authorId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string authorId = 3;</code>
     */
    public Builder clearAuthorId() {
      
      authorId_ = getDefaultInstance().getAuthorId();
      onChanged();
      return this;
    }
    /**
     * <code>string authorId = 3;</code>
     */
    public Builder setAuthorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      authorId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object createdAt_ = "";
    /**
     * <code>string createdAt = 4;</code>
     */
    public java.lang.String getCreatedAt() {
      java.lang.Object ref = createdAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdAt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string createdAt = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedAtBytes() {
      java.lang.Object ref = createdAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string createdAt = 4;</code>
     */
    public Builder setCreatedAt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createdAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string createdAt = 4;</code>
     */
    public Builder clearCreatedAt() {
      
      createdAt_ = getDefaultInstance().getCreatedAt();
      onChanged();
      return this;
    }
    /**
     * <code>string createdAt = 4;</code>
     */
    public Builder setCreatedAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createdAt_ = value;
      onChanged();
      return this;
    }

    private double negativeScore_ ;
    /**
     * <code>double negativeScore = 5;</code>
     */
    public double getNegativeScore() {
      return negativeScore_;
    }
    /**
     * <code>double negativeScore = 5;</code>
     */
    public Builder setNegativeScore(double value) {
      
      negativeScore_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double negativeScore = 5;</code>
     */
    public Builder clearNegativeScore() {
      
      negativeScore_ = 0D;
      onChanged();
      return this;
    }

    private double neutralScore_ ;
    /**
     * <code>double neutralScore = 6;</code>
     */
    public double getNeutralScore() {
      return neutralScore_;
    }
    /**
     * <code>double neutralScore = 6;</code>
     */
    public Builder setNeutralScore(double value) {
      
      neutralScore_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double neutralScore = 6;</code>
     */
    public Builder clearNeutralScore() {
      
      neutralScore_ = 0D;
      onChanged();
      return this;
    }

    private double positiveScore_ ;
    /**
     * <code>double positiveScore = 7;</code>
     */
    public double getPositiveScore() {
      return positiveScore_;
    }
    /**
     * <code>double positiveScore = 7;</code>
     */
    public Builder setPositiveScore(double value) {
      
      positiveScore_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double positiveScore = 7;</code>
     */
    public Builder clearPositiveScore() {
      
      positiveScore_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TweetData)
  }

  // @@protoc_insertion_point(class_scope:TweetData)
  private static final com.talentica.tweetsservicegrpc.TweetData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.talentica.tweetsservicegrpc.TweetData();
  }

  public static com.talentica.tweetsservicegrpc.TweetData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TweetData>
      PARSER = new com.google.protobuf.AbstractParser<TweetData>() {
    @java.lang.Override
    public TweetData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TweetData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TweetData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TweetData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.talentica.tweetsservicegrpc.TweetData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

