// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TweetsService.proto

package com.talentica.tweetsservicegrpc;

public interface TweetDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TweetData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string text = 2;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 2;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>string authorId = 3;</code>
   */
  java.lang.String getAuthorId();
  /**
   * <code>string authorId = 3;</code>
   */
  com.google.protobuf.ByteString
      getAuthorIdBytes();

  /**
   * <code>string createdAt = 4;</code>
   */
  java.lang.String getCreatedAt();
  /**
   * <code>string createdAt = 4;</code>
   */
  com.google.protobuf.ByteString
      getCreatedAtBytes();

  /**
   * <code>string userName = 5;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 5;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string userHandle = 6;</code>
   */
  java.lang.String getUserHandle();
  /**
   * <code>string userHandle = 6;</code>
   */
  com.google.protobuf.ByteString
      getUserHandleBytes();

  /**
   * <code>string userLocation = 7;</code>
   */
  java.lang.String getUserLocation();
  /**
   * <code>string userLocation = 7;</code>
   */
  com.google.protobuf.ByteString
      getUserLocationBytes();

  /**
   * <code>bool isVerified = 8;</code>
   */
  boolean getIsVerified();

  /**
   * <code>int32 followersCount = 9;</code>
   */
  int getFollowersCount();

  /**
   * <code>int32 tweetCount = 10;</code>
   */
  int getTweetCount();

  /**
   * <code>double negativeScore = 11;</code>
   */
  double getNegativeScore();

  /**
   * <code>double neutralScore = 12;</code>
   */
  double getNeutralScore();

  /**
   * <code>double positiveScore = 13;</code>
   */
  double getPositiveScore();
}
