// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TweetsService.proto

package com.talentica.tweetsservicegrpc;

public interface TweetDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TweetData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string text = 2;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 2;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>string authorId = 3;</code>
   */
  java.lang.String getAuthorId();
  /**
   * <code>string authorId = 3;</code>
   */
  com.google.protobuf.ByteString
      getAuthorIdBytes();

  /**
   * <code>string createdAt = 4;</code>
   */
  java.lang.String getCreatedAt();
  /**
   * <code>string createdAt = 4;</code>
   */
  com.google.protobuf.ByteString
      getCreatedAtBytes();

  /**
   * <code>double negativeScore = 5;</code>
   */
  double getNegativeScore();

  /**
   * <code>double neutralScore = 6;</code>
   */
  double getNeutralScore();

  /**
   * <code>double positiveScore = 7;</code>
   */
  double getPositiveScore();
}
